
### 
GET http://localhost:3000/api/todos


### 
GET http://localhost:3000/api/todos/1


### 
DELETE http://localhost:3000/api/todos/27


### 
PATCH http://localhost:3000/api/todos  HTTP/1.1
content-type: application/json

{ 
    "id": 26,
    "title": "zied abbassi",
    "completed": true
}
